/*
 * Honeywell TruStability HSC Series pressure/temperature sensor
 *
 * Copyright (c) 2024 Petre Rodan <2b4eda@subdimension.ro>
 *
 * (7-bit I2C slave address can be 0x28, 0x38, 0x48, 0x58,
                                        0x68, 0x78, 0x88 or 0x98)
 *
 * Datasheet: https://prod-edam.honeywell.com/content/dam/honeywell-edam/sps/siot/en-us/products/sensors/pressure-sensors/board-mount-pressure-sensors/trustability-hsc-series/documents/sps-siot-trustability-hsc-series-high-accuracy-board-mount-pressure-sensors-50099148-a-en-ciid-151133.pdf?download=false
 * Website: https://sps.honeywell.com/us/en/products/advanced-sensing-technologies/healthcare-sensing/board-mount-pressure-sensors/trustability-hsc-series#resources
 * i2c datasheet: https://prod-edam.honeywell.com/content/dam/honeywell-edam/sps/siot/en-us/products/sensors/pressure-sensors/board-mount-pressure-sensors/common/documents/sps-siot-i2c-comms-digital-output-pressure-sensors-tn-008201-3-en-ciid-45841.pdf?download=false
 */

#include <linux/module.h>
#include <linux/mutex.h>
#include <linux/init.h>
#include <linux/i2c.h>
#include <linux/mod_devicetable.h>
#include <linux/printk.h>

#include <linux/iio/iio.h>
#include <linux/iio/sysfs.h>

#define HSC_REG_MEASUREMENT_RD_SIZE 4

struct hsc_chip_data;

struct hsc_config {
	int min;
	int max;
};

struct hsc_data {
	struct i2c_client *client;
	const struct hsc_chip_data *chip;
	struct mutex lock;
	int (*xfer)(struct hsc_data * data);
	bool is_valid;
	unsigned long last_update;
	u8 buffer[4];
	int min;
	int max;
};

struct hsc_chip_data {
	bool (*valid)(struct hsc_data * data);
	const struct iio_chan_spec *channels;
	u8 num_channels;
	u8 read_size;
};

enum hsc_variant {
         HSC001BA, HSC1_6BA, HSC2_5BA, HSC004BA, HSC006BA, HSC010BA,
         HSC1_6MD, HSC2_5MD, HSC004MD, HSC006MD, HSC010MD, HSC016MD,
         HSC025MD, HSC040MD, HSC060MD, HSC100MD, HSC160MD, HSC250MD,
         HSC400MD, HSC600MD, HSC001BD, HSC1_6BD, HSC2_5BD, HSC004BD,
         HSC2_5MG, HSC004MG, HSC006MG, HSC010MG, HSC016MG, HSC025MG,
         HSC040MG, HSC060MG, HSC100MG, HSC160MG, HSC250MG, HSC400MG,
         HSC600MG, HSC001BG, HSC1_6BG, HSC2_5BG, HSC004BG, HSC006BG,
         HSC010BG, HSC100KA, HSC160KA, HSC250KA, HSC400KA, HSC600KA,
         HSC001GA, HSC160LD, HSC250LD, HSC400LD, HSC600LD, HSC001KD,
         HSC1_6KD, HSC2_5KD, HSC004KD, HSC006KD, HSC010KD, HSC016KD,
         HSC025KD, HSC040KD, HSC060KD, HSC100KD, HSC160KD, HSC250KD,
         HSC400KD, HSC250LG, HSC400LG, HSC600LG, HSC001KG, HSC1_6KG,
         HSC2_5KG, HSC004KG, HSC006KG, HSC010KG, HSC016KG, HSC025KG,
         HSC040KG, HSC060KG, HSC100KG, HSC160KG, HSC250KG, HSC400KG,
         HSC600KG, HSC001GG, HSC015PA, HSC030PA, HSC060PA, HSC100PA,
         HSC150PA, HSC0_5ND, HSC001ND, HSC002ND, HSC004ND, HSC005ND,
         HSC010ND, HSC020ND, HSC030ND, HSC001PD, HSC005PD, HSC015PD,
         HSC030PD, HSC060PD, HSC001NG, HSC002NG, HSC004NG, HSC005NG,
         HSC010NG, HSC020NG, HSC030NG, HSC001PG, HSC005PG, HSC015PG,
         HSC030PG, HSC060PG, HSC100PG, HSC150PG,
};

// all min max limits have been converted to pascals
// code generated by scripts/parse_variants_tabls.sh
static struct hsc_config hsc_config[] = {
	[HSC001BA] = { .min =       0, .max =  100000 },
	[HSC1_6BA] = { .min =       0, .max =  160000 },
	[HSC2_5BA] = { .min =       0, .max =  250000 },
	[HSC004BA] = { .min =       0, .max =  400000 },
	[HSC006BA] = { .min =       0, .max =  600000 },
	[HSC010BA] = { .min =       0, .max = 1000000 },
	[HSC1_6MD] = { .min =    -160, .max =     160 },
	[HSC2_5MD] = { .min =    -250, .max =     250 },
	[HSC004MD] = { .min =    -400, .max =     400 },
	[HSC006MD] = { .min =    -600, .max =     600 },
	[HSC010MD] = { .min =   -1000, .max =    1000 },
	[HSC016MD] = { .min =   -1600, .max =    1600 },
	[HSC025MD] = { .min =   -2500, .max =    2500 },
	[HSC040MD] = { .min =   -4000, .max =    4000 },
	[HSC060MD] = { .min =   -6000, .max =    6000 },
	[HSC100MD] = { .min =  -10000, .max =   10000 },
	[HSC160MD] = { .min =  -16000, .max =   16000 },
	[HSC250MD] = { .min =  -25000, .max =   25000 },
	[HSC400MD] = { .min =  -40000, .max =   40000 },
	[HSC600MD] = { .min =  -60000, .max =   60000 },
	[HSC001BD] = { .min = -100000, .max =  100000 },
	[HSC1_6BD] = { .min = -160000, .max =  160000 },
	[HSC2_5BD] = { .min = -250000, .max =  250000 },
	[HSC004BD] = { .min = -400000, .max =  400000 },
	[HSC2_5MG] = { .min =       0, .max =     250 },
	[HSC004MG] = { .min =       0, .max =     400 },
	[HSC006MG] = { .min =       0, .max =     600 },
	[HSC010MG] = { .min =       0, .max =    1000 },
	[HSC016MG] = { .min =       0, .max =    1600 },
	[HSC025MG] = { .min =       0, .max =    2500 },
	[HSC040MG] = { .min =       0, .max =    4000 },
	[HSC060MG] = { .min =       0, .max =    6000 },
	[HSC100MG] = { .min =       0, .max =   10000 },
	[HSC160MG] = { .min =       0, .max =   16000 },
	[HSC250MG] = { .min =       0, .max =   25000 },
	[HSC400MG] = { .min =       0, .max =   40000 },
	[HSC600MG] = { .min =       0, .max =   60000 },
	[HSC001BG] = { .min =       0, .max =  100000 },
	[HSC1_6BG] = { .min =       0, .max =  160000 },
	[HSC2_5BG] = { .min =       0, .max =  250000 },
	[HSC004BG] = { .min =       0, .max =  400000 },
	[HSC006BG] = { .min =       0, .max =  600000 },
	[HSC010BG] = { .min =       0, .max = 1000000 },
	[HSC100KA] = { .min =       0, .max =  100000 },
	[HSC160KA] = { .min =       0, .max =  160000 },
	[HSC250KA] = { .min =       0, .max =  250000 },
	[HSC400KA] = { .min =       0, .max =  400000 },
	[HSC600KA] = { .min =       0, .max =  600000 },
	[HSC001GA] = { .min =       0, .max = 1000000 },
	[HSC160LD] = { .min =    -160, .max =     160 },
	[HSC250LD] = { .min =    -250, .max =     250 },
	[HSC400LD] = { .min =    -400, .max =     400 },
	[HSC600LD] = { .min =    -600, .max =     600 },
	[HSC001KD] = { .min =   -1000, .max =    1000 },
	[HSC1_6KD] = { .min =   -1600, .max =    1600 },
	[HSC2_5KD] = { .min =   -2500, .max =    2500 },
	[HSC004KD] = { .min =   -4000, .max =    4000 },
	[HSC006KD] = { .min =   -6000, .max =    6000 },
	[HSC010KD] = { .min =  -10000, .max =   10000 },
	[HSC016KD] = { .min =  -16000, .max =   16000 },
	[HSC025KD] = { .min =  -25000, .max =   25000 },
	[HSC040KD] = { .min =  -40000, .max =   40000 },
	[HSC060KD] = { .min =  -60000, .max =   60000 },
	[HSC100KD] = { .min = -100000, .max =  100000 },
	[HSC160KD] = { .min = -160000, .max =  160000 },
	[HSC250KD] = { .min = -250000, .max =  250000 },
	[HSC400KD] = { .min = -400000, .max =  400000 },
	[HSC250LG] = { .min =       0, .max =     250 },
	[HSC400LG] = { .min =       0, .max =     400 },
	[HSC600LG] = { .min =       0, .max =     600 },
	[HSC001KG] = { .min =       0, .max =    1000 },
	[HSC1_6KG] = { .min =       0, .max =    1600 },
	[HSC2_5KG] = { .min =       0, .max =    2500 },
	[HSC004KG] = { .min =       0, .max =    4000 },
	[HSC006KG] = { .min =       0, .max =    6000 },
	[HSC010KG] = { .min =       0, .max =   10000 },
	[HSC016KG] = { .min =       0, .max =   16000 },
	[HSC025KG] = { .min =       0, .max =   25000 },
	[HSC040KG] = { .min =       0, .max =   40000 },
	[HSC060KG] = { .min =       0, .max =   60000 },
	[HSC100KG] = { .min =       0, .max =  100000 },
	[HSC160KG] = { .min =       0, .max =  160000 },
	[HSC250KG] = { .min =       0, .max =  250000 },
	[HSC400KG] = { .min =       0, .max =  400000 },
	[HSC600KG] = { .min =       0, .max =  600000 },
	[HSC001GG] = { .min =       0, .max = 1000000 },
	[HSC015PA] = { .min =       0, .max =  103425 },
	[HSC030PA] = { .min =       0, .max =  206850 },
	[HSC060PA] = { .min =       0, .max =  413700 },
	[HSC100PA] = { .min =       0, .max =  689500 },
	[HSC150PA] = { .min =       0, .max = 1034250 },
	[HSC0_5ND] = { .min =    -125, .max =     125 },
	[HSC001ND] = { .min =    -249, .max =     249 },
	[HSC002ND] = { .min =    -498, .max =     498 },
	[HSC004ND] = { .min =    -996, .max =     996 },
	[HSC005ND] = { .min =   -1245, .max =    1245 },
	[HSC010ND] = { .min =   -2491, .max =    2491 },
	[HSC020ND] = { .min =   -4982, .max =    4982 },
	[HSC030ND] = { .min =   -7473, .max =    7473 },
	[HSC001PD] = { .min =   -6895, .max =    6895 },
	[HSC005PD] = { .min =  -34475, .max =   34475 },
	[HSC015PD] = { .min = -103425, .max =  103425 },
	[HSC030PD] = { .min = -206850, .max =  206850 },
	[HSC060PD] = { .min = -413700, .max =  413700 },
	[HSC001NG] = { .min =       0, .max =     249 },
	[HSC002NG] = { .min =       0, .max =     498 },
	[HSC004NG] = { .min =       0, .max =     996 },
	[HSC005NG] = { .min =       0, .max =    1245 },
	[HSC010NG] = { .min =       0, .max =    2491 },
	[HSC020NG] = { .min =       0, .max =    4982 },
	[HSC030NG] = { .min =       0, .max =    7473 },
	[HSC001PG] = { .min =       0, .max =    6895 },
	[HSC005PG] = { .min =       0, .max =   34475 },
	[HSC015PG] = { .min =       0, .max =  103425 },
	[HSC030PG] = { .min =       0, .max =  206850 },
	[HSC060PG] = { .min =       0, .max =  413700 },
	[HSC100PG] = { .min =       0, .max =  689500 },
	[HSC150PG] = { .min =       0, .max = 1034250 },
};

static IIO_CONST_ATTR(in_concentration_temp_scale, "0.00000698689");
static IIO_CONST_ATTR(in_concentration_pres_scale, "0.00000000436681223");

static struct attribute *hsc_attributes[] = {
	&iio_const_attr_in_concentration_temp_scale.dev_attr.attr,
	&iio_const_attr_in_concentration_pres_scale.dev_attr.attr,
	NULL,
};

static const struct attribute_group hsc_attrs_group = {
	.attrs = hsc_attributes,
};

static bool hsc_measurement_is_valid(struct hsc_data *data)
{
	return true;
}

static int hsc_i2c_xfer(struct hsc_data *data)
{
	const struct hsc_chip_data *chip = data->chip;
	struct i2c_client *client = data->client;
	struct i2c_msg msg;
	int ret;

	msg.addr = client->addr;
	msg.flags = client->flags | I2C_M_RD;
	msg.len = chip->read_size;
	msg.buf = (char *)&data->buffer;

	ret = i2c_transfer(client->adapter, &msg, 1);

	return (ret == 2) ? 0 : ret;
}

static int hsc_smbus_xfer(struct hsc_data *data)
{
	pr_info("smb xfer not implemented\n");
	return 0;
}

static int hsc_get_measurement(struct hsc_data *data)
{
	int ret;

	/* don't bother sensor more than once a second */
	if (!time_after(jiffies, data->last_update + HZ)) {
		return data->is_valid ? 0 : -EAGAIN;
	}

	data->is_valid = false;
	data->last_update = jiffies;

	ret = data->xfer(data);

	pr_info("recvd %02x %02x %02x %02x\n", data->buffer[0], data->buffer[1],
		data->buffer[2], data->buffer[3]);
	if (ret < 0)
		return ret;

#if 0
	ret = chip->valid(data);
	if (ret)
		return -EAGAIN;
#endif

	data->is_valid = true;

	return 0;
}

static int hsc_read_raw(struct iio_dev *indio_dev,
			struct iio_chan_spec const *channel, int *val,
			int *val2, long mask)
{
	struct hsc_data *data = iio_priv(indio_dev);
	int ret = -EINVAL;

	switch (mask) {

	case IIO_CHAN_INFO_RAW:
		mutex_lock(&data->lock);
		ret = hsc_get_measurement(data);
		mutex_unlock(&data->lock);

		if (ret)
			return ret;

		switch (channel->type) {
		case IIO_PRESSURE:
			*val =
			    ((data->buffer[0] & 0x3f) << 8) + data->buffer[1];
			return IIO_VAL_INT;
		case IIO_TEMP:
			*val =
			    ((data->buffer[2] << 8) +
			     (data->buffer[3] & 0xe0)) >> 5;
			ret = 0;
			if (!ret)
				return IIO_VAL_INT;
			break;
		default:
			return -EINVAL;
		}
		break;

	case IIO_CHAN_INFO_SCALE:
		switch (channel->type) {
		case IIO_PRESSURE:
			*val = 10;
			return IIO_VAL_INT;
		default:
			return -EINVAL;
		}
		break;

	case IIO_CHAN_INFO_OFFSET:
		switch (channel->channel2) {
		case IIO_PRESSURE:
			*val = 44;
			*val2 = 250000;
			return IIO_VAL_INT_PLUS_MICRO;
		case IIO_TEMP:
			*val = -13;
			return IIO_VAL_INT;
		default:
			return -EINVAL;
		}
	}

	return ret;
}

static const struct iio_chan_spec hsc_channels[] = {
	{
	 .type = IIO_PRESSURE,
	 .info_mask_separate = BIT(IIO_CHAN_INFO_OFFSET) |
	 BIT(IIO_CHAN_INFO_RAW) | BIT(IIO_CHAN_INFO_PROCESSED),
	 },
	{
	 .type = IIO_TEMP,
	 .info_mask_separate = BIT(IIO_CHAN_INFO_PROCESSED) |
	 BIT(IIO_CHAN_INFO_RAW) | BIT(IIO_CHAN_INFO_OFFSET),
	 },
};

static const struct iio_info hsc_info = {
	.attrs = &hsc_attrs_group,
	.read_raw = hsc_read_raw,
};

static const struct hsc_chip_data hsc_chips[] = {
	{
	 .valid = hsc_measurement_is_valid,
	 .read_size = HSC_REG_MEASUREMENT_RD_SIZE,

	 .channels = hsc_channels,
	 .num_channels = ARRAY_SIZE(hsc_channels),
	 },
};

static int hsc_probe(struct i2c_client *client, const struct i2c_device_id *id)
{
	struct device *dev = &client->dev;
	struct iio_dev *indio_dev;
	struct hsc_data *hsc;
	struct hsc_config *config;
	int chip_id;

	indio_dev = devm_iio_device_alloc(dev, sizeof(*hsc));
	if (!indio_dev) {
		dev_err(&client->dev, "Failed to allocate device\n");
		return -ENOMEM;
	}

	hsc = iio_priv(indio_dev);

	if (i2c_check_functionality(client->adapter, I2C_FUNC_I2C)) {
		hsc->xfer = hsc_i2c_xfer;
	} else if (i2c_check_functionality(client->adapter,
					   I2C_FUNC_SMBUS_WORD_DATA |
					   I2C_FUNC_SMBUS_BYTE)) {
		hsc->xfer = hsc_smbus_xfer;
		pr_info("start to panic, smbus selected\n");
	} else {
		return -EOPNOTSUPP;
	}

#if 0
	if (!dev_fwnode(dev)) {
		chip_id = id->driver_data;
	} else {
		// always happens and chip_id is always zero :/
		chip_id = (unsigned long)device_get_match_data(dev);
	}
#else
	dev_fwnode(dev);
	chip_id = id->driver_data;
#endif

	pr_info("hsc id 0x%02x found\n", chip_id);
	config = &hsc_config[chip_id];
	i2c_set_clientdata(client, indio_dev);
	hsc->client = client;
	hsc->chip = &hsc_chips[0];
	hsc->last_update = jiffies - HZ;

	hsc->min = config->min;
	hsc->max = config->max;
	//hsc->scale = config->max - config->min;

	mutex_init(&hsc->lock);
	indio_dev->name = id->name;
	indio_dev->modes = INDIO_DIRECT_MODE;
	indio_dev->info = &hsc_info;
	indio_dev->channels = hsc->chip->channels;
	indio_dev->num_channels = hsc->chip->num_channels;

	return devm_iio_device_register(dev, indio_dev);
}

static void hsc_remove(struct i2c_client *client)
{
	// FIXME
}

static const struct of_device_id hsc_of_match[] = {
	{ .compatible = "honeywell,hsc001ba",}, { .compatible = "honeywell,hsc1.6ba",},
	{ .compatible = "honeywell,hsc2.5ba",}, { .compatible = "honeywell,hsc004ba",},
	{ .compatible = "honeywell,hsc006ba",}, { .compatible = "honeywell,hsc010ba",},
	{ .compatible = "honeywell,hsc1.6md",}, { .compatible = "honeywell,hsc2.5md",},
	{ .compatible = "honeywell,hsc004md",}, { .compatible = "honeywell,hsc006md",},
	{ .compatible = "honeywell,hsc010md",}, { .compatible = "honeywell,hsc016md",},
	{ .compatible = "honeywell,hsc025md",}, { .compatible = "honeywell,hsc040md",},
	{ .compatible = "honeywell,hsc060md",}, { .compatible = "honeywell,hsc100md",},
	{ .compatible = "honeywell,hsc160md",}, { .compatible = "honeywell,hsc250md",},
	{ .compatible = "honeywell,hsc400md",}, { .compatible = "honeywell,hsc600md",},
	{ .compatible = "honeywell,hsc001bd",}, { .compatible = "honeywell,hsc1.6bd",},
	{ .compatible = "honeywell,hsc2.5bd",}, { .compatible = "honeywell,hsc004bd",},
	{ .compatible = "honeywell,hsc2.5mg",}, { .compatible = "honeywell,hsc004mg",},
	{ .compatible = "honeywell,hsc006mg",}, { .compatible = "honeywell,hsc010mg",},
	{ .compatible = "honeywell,hsc016mg",}, { .compatible = "honeywell,hsc025mg",},
	{ .compatible = "honeywell,hsc040mg",}, { .compatible = "honeywell,hsc060mg",},
	{ .compatible = "honeywell,hsc100mg",}, { .compatible = "honeywell,hsc160mg",},
	{ .compatible = "honeywell,hsc250mg",}, { .compatible = "honeywell,hsc400mg",},
	{ .compatible = "honeywell,hsc600mg",}, { .compatible = "honeywell,hsc001bg",},
	{ .compatible = "honeywell,hsc1.6bg",}, { .compatible = "honeywell,hsc2.5bg",},
	{ .compatible = "honeywell,hsc004bg",}, { .compatible = "honeywell,hsc006bg",},
	{ .compatible = "honeywell,hsc010bg",}, { .compatible = "honeywell,hsc100ka",},
	{ .compatible = "honeywell,hsc160ka",}, { .compatible = "honeywell,hsc250ka",},
	{ .compatible = "honeywell,hsc400ka",}, { .compatible = "honeywell,hsc600ka",},
	{ .compatible = "honeywell,hsc001ga",}, { .compatible = "honeywell,hsc160ld",},
	{ .compatible = "honeywell,hsc250ld",}, { .compatible = "honeywell,hsc400ld",},
	{ .compatible = "honeywell,hsc600ld",}, { .compatible = "honeywell,hsc001kd",},
	{ .compatible = "honeywell,hsc1.6kd",}, { .compatible = "honeywell,hsc2.5kd",},
	{ .compatible = "honeywell,hsc004kd",}, { .compatible = "honeywell,hsc006kd",},
	{ .compatible = "honeywell,hsc010kd",}, { .compatible = "honeywell,hsc016kd",},
	{ .compatible = "honeywell,hsc025kd",}, { .compatible = "honeywell,hsc040kd",},
	{ .compatible = "honeywell,hsc060kd",}, { .compatible = "honeywell,hsc100kd",},
	{ .compatible = "honeywell,hsc160kd",}, { .compatible = "honeywell,hsc250kd",},
	{ .compatible = "honeywell,hsc400kd",}, { .compatible = "honeywell,hsc250lg",},
	{ .compatible = "honeywell,hsc400lg",}, { .compatible = "honeywell,hsc600lg",},
	{ .compatible = "honeywell,hsc001kg",}, { .compatible = "honeywell,hsc1.6kg",},
	{ .compatible = "honeywell,hsc2.5kg",}, { .compatible = "honeywell,hsc004kg",},
	{ .compatible = "honeywell,hsc006kg",}, { .compatible = "honeywell,hsc010kg",},
	{ .compatible = "honeywell,hsc016kg",}, { .compatible = "honeywell,hsc025kg",},
	{ .compatible = "honeywell,hsc040kg",}, { .compatible = "honeywell,hsc060kg",},
	{ .compatible = "honeywell,hsc100kg",}, { .compatible = "honeywell,hsc160kg",},
	{ .compatible = "honeywell,hsc250kg",}, { .compatible = "honeywell,hsc400kg",},
	{ .compatible = "honeywell,hsc600kg",}, { .compatible = "honeywell,hsc001gg",},
	{ .compatible = "honeywell,hsc015pa",}, { .compatible = "honeywell,hsc030pa",},
	{ .compatible = "honeywell,hsc060pa",}, { .compatible = "honeywell,hsc100pa",},
	{ .compatible = "honeywell,hsc150pa",}, { .compatible = "honeywell,hsc0.5nd",},
	{ .compatible = "honeywell,hsc001nd",}, { .compatible = "honeywell,hsc002nd",},
	{ .compatible = "honeywell,hsc004nd",}, { .compatible = "honeywell,hsc005nd",},
	{ .compatible = "honeywell,hsc010nd",}, { .compatible = "honeywell,hsc020nd",},
	{ .compatible = "honeywell,hsc030nd",}, { .compatible = "honeywell,hsc001pd",},
	{ .compatible = "honeywell,hsc005pd",}, { .compatible = "honeywell,hsc015pd",},
	{ .compatible = "honeywell,hsc030pd",}, { .compatible = "honeywell,hsc060pd",},
	{ .compatible = "honeywell,hsc001ng",}, { .compatible = "honeywell,hsc002ng",},
	{ .compatible = "honeywell,hsc004ng",}, { .compatible = "honeywell,hsc005ng",},
	{ .compatible = "honeywell,hsc010ng",}, { .compatible = "honeywell,hsc020ng",},
	{ .compatible = "honeywell,hsc030ng",}, { .compatible = "honeywell,hsc001pg",},
	{ .compatible = "honeywell,hsc005pg",}, { .compatible = "honeywell,hsc015pg",},
	{ .compatible = "honeywell,hsc030pg",}, { .compatible = "honeywell,hsc060pg",},
	{ .compatible = "honeywell,hsc100pg",}, { .compatible = "honeywell,hsc150pg",},
	{},
};

MODULE_DEVICE_TABLE(of, hsc_of_match);

static const struct i2c_device_id hsc_id[] = {
	{ "hsc001ba", HSC001BA }, { "hsc1.6ba", HSC1_6BA },
	{ "hsc2.5ba", HSC2_5BA }, { "hsc004ba", HSC004BA },
	{ "hsc006ba", HSC006BA }, { "hsc010ba", HSC010BA },
	{ "hsc1.6md", HSC1_6MD }, { "hsc2.5md", HSC2_5MD },
	{ "hsc004md", HSC004MD }, { "hsc006md", HSC006MD },
	{ "hsc010md", HSC010MD }, { "hsc016md", HSC016MD },
	{ "hsc025md", HSC025MD }, { "hsc040md", HSC040MD },
	{ "hsc060md", HSC060MD }, { "hsc100md", HSC100MD },
	{ "hsc160md", HSC160MD }, { "hsc250md", HSC250MD },
	{ "hsc400md", HSC400MD }, { "hsc600md", HSC600MD },
	{ "hsc001bd", HSC001BD }, { "hsc1.6bd", HSC1_6BD },
	{ "hsc2.5bd", HSC2_5BD }, { "hsc004bd", HSC004BD },
	{ "hsc2.5mg", HSC2_5MG }, { "hsc004mg", HSC004MG },
	{ "hsc006mg", HSC006MG }, { "hsc010mg", HSC010MG },
	{ "hsc016mg", HSC016MG }, { "hsc025mg", HSC025MG },
	{ "hsc040mg", HSC040MG }, { "hsc060mg", HSC060MG },
	{ "hsc100mg", HSC100MG }, { "hsc160mg", HSC160MG },
	{ "hsc250mg", HSC250MG }, { "hsc400mg", HSC400MG },
	{ "hsc600mg", HSC600MG }, { "hsc001bg", HSC001BG },
	{ "hsc1.6bg", HSC1_6BG }, { "hsc2.5bg", HSC2_5BG },
	{ "hsc004bg", HSC004BG }, { "hsc006bg", HSC006BG },
	{ "hsc010bg", HSC010BG }, { "hsc100ka", HSC100KA },
	{ "hsc160ka", HSC160KA }, { "hsc250ka", HSC250KA },
	{ "hsc400ka", HSC400KA }, { "hsc600ka", HSC600KA },
	{ "hsc001ga", HSC001GA }, { "hsc160ld", HSC160LD },
	{ "hsc250ld", HSC250LD }, { "hsc400ld", HSC400LD },
	{ "hsc600ld", HSC600LD }, { "hsc001kd", HSC001KD },
	{ "hsc1.6kd", HSC1_6KD }, { "hsc2.5kd", HSC2_5KD },
	{ "hsc004kd", HSC004KD }, { "hsc006kd", HSC006KD },
	{ "hsc010kd", HSC010KD }, { "hsc016kd", HSC016KD },
	{ "hsc025kd", HSC025KD }, { "hsc040kd", HSC040KD },
	{ "hsc060kd", HSC060KD }, { "hsc100kd", HSC100KD },
	{ "hsc160kd", HSC160KD }, { "hsc250kd", HSC250KD },
	{ "hsc400kd", HSC400KD }, { "hsc250lg", HSC250LG },
	{ "hsc400lg", HSC400LG }, { "hsc600lg", HSC600LG },
	{ "hsc001kg", HSC001KG }, { "hsc1.6kg", HSC1_6KG },
	{ "hsc2.5kg", HSC2_5KG }, { "hsc004kg", HSC004KG },
	{ "hsc006kg", HSC006KG }, { "hsc010kg", HSC010KG },
	{ "hsc016kg", HSC016KG }, { "hsc025kg", HSC025KG },
	{ "hsc040kg", HSC040KG }, { "hsc060kg", HSC060KG },
	{ "hsc100kg", HSC100KG }, { "hsc160kg", HSC160KG },
	{ "hsc250kg", HSC250KG }, { "hsc400kg", HSC400KG },
	{ "hsc600kg", HSC600KG }, { "hsc001gg", HSC001GG },
	{ "hsc015pa", HSC015PA }, { "hsc030pa", HSC030PA },
	{ "hsc060pa", HSC060PA }, { "hsc100pa", HSC100PA },
	{ "hsc150pa", HSC150PA }, { "hsc0.5nd", HSC0_5ND },
	{ "hsc001nd", HSC001ND }, { "hsc002nd", HSC002ND },
	{ "hsc004nd", HSC004ND }, { "hsc005nd", HSC005ND },
	{ "hsc010nd", HSC010ND }, { "hsc020nd", HSC020ND },
	{ "hsc030nd", HSC030ND }, { "hsc001pd", HSC001PD },
	{ "hsc005pd", HSC005PD }, { "hsc015pd", HSC015PD },
	{ "hsc030pd", HSC030PD }, { "hsc060pd", HSC060PD },
	{ "hsc001ng", HSC001NG }, { "hsc002ng", HSC002NG },
	{ "hsc004ng", HSC004NG }, { "hsc005ng", HSC005NG },
	{ "hsc010ng", HSC010NG }, { "hsc020ng", HSC020NG },
	{ "hsc030ng", HSC030NG }, { "hsc001pg", HSC001PG },
	{ "hsc005pg", HSC005PG }, { "hsc015pg", HSC015PG },
	{ "hsc030pg", HSC030PG }, { "hsc060pg", HSC060PG },
	{ "hsc100pg", HSC100PG }, { "hsc150pg", HSC150PG },
	{}
};

MODULE_DEVICE_TABLE(i2c, hsc_id);

static struct i2c_driver hsc_driver = {
	.driver = {
		   .name = "honeywell_hsc",
		   .of_match_table = hsc_of_match,
		   },
	.probe = hsc_probe,
	.remove = hsc_remove,
	.id_table = hsc_id,
};

module_i2c_driver(hsc_driver);

MODULE_AUTHOR("Petre Rodan <2b4eda@subdimension.ro>");
MODULE_DESCRIPTION("Honeywell HSC pressure sensor driver");
MODULE_LICENSE("GPL");
